spring:
  application:
    name: todo-high
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=todo_high
    username: postgres
    password: 123456
  flyway:
    default-schema: todo_high
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: 123456
