scheme: http
hostname: localhost
reverse-proxy-port: 7080
reverse-proxy-uri: ${scheme}://${hostname}:${reverse-proxy-port}
authorization-server-prefix: /admin
issuer: ${reverse-proxy-uri}/realms/associacao_manager
username-claim-json-path: $.preferred_username
authorities-json-path: $.realm_access.roles
resource-server-port: 7084
audience:

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: ${issuer}
            username-claim: ${username-claim-json-path}
            authorities:
              - path: ${authorities-json-path}
            aud: ${audience}
        resourceserver:
          permit-all:
            - /me

spring:
  application:
    name: associacao-back
  datasource:
    url: url
    username: postgres
    password: password
  flyway:
    default-schema: associacao_dev
    url: url
    user: postgres
    password: password

server:
  port: ${resource-server-port}
